name: Build and Deploy storybook docs to GH Pages

on:
  push:
    # Trigger only on the main branch
    branches:
      - main
    # Trigger the action only when files change in the folders defined here
    paths: [".storybook/**", "src/**"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build
        # Install npm packages and build the Storybook files
        run: |
          yarn install
          yarn build-storybook
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # The branch the action should deploy to
          BRANCH: main
          # The folder that the build-storybook script generates files
          FOLDER: docs-build
          # Automatically remove deleted files from the deploy branch
          CLEAN: true
          # Target the expected output folder for GH Pages
          TARGET_FOLDER: docs
